/**
 * Absolute URLs for the static assets the templates load.
 *
 * Email clients can only fetch images from a public absolute URL, so the files
 * live in `apps/web/public/email/` (generated by
 * `scripts/generate-email-assets.ts`) and are served by the web app. That means
 * the web deploy that ships those files must go out BEFORE any template that
 * references a new one sends real mail.
 *
 * `EMAIL_ASSET_BASE_URL` overrides the origin (e.g. a preview deployment). It is
 * read at render time, not import time, so tests and scripts can set it.
 */
export const DEFAULT_EMAIL_ASSET_BASE_URL = 'https://getpropertypro.com/email';

export const EMAIL_ICONS = [
  'alert-red',
  'alert-white',
  'bell-slate',
  'calendar-coral',
  'check-green',
  'clock-amber',
  'clock-red',
  'clock-slate',
  'dashboard-coral',
  'doc-coral',
  'doc-slate',
  'download-amber',
  'download-slate',
  'lock-coral',
  'lock-slate',
  'megaphone-coral',
  'megaphone-slate',
  'money-red',
  'money-slate',
  'pen-violet',
  'shield-coral',
  'shield-teal',
  'user-slate',
  'user-teal',
  'warn-amber',
] as const;

export type EmailIcon = (typeof EMAIL_ICONS)[number];

export const EMAIL_IMAGES = [
  'logomark-ink.png',
  'photo-coast.jpg',
  'photo-condo.jpg',
  'band-records.jpg',
] as const;

export type EmailImage = (typeof EMAIL_IMAGES)[number];

export function emailAssetBaseUrl(): string {
  const configured = process.env.EMAIL_ASSET_BASE_URL?.trim();
  return (configured || DEFAULT_EMAIL_ASSET_BASE_URL).replace(/\/+$/, '');
}

export function emailIconUrl(icon: EmailIcon): string {
  return `${emailAssetBaseUrl()}/icons/${icon}.png`;
}

export function emailImageUrl(image: EmailImage): string {
  return `${emailAssetBaseUrl()}/${image}`;
}

export function emailFontUrl(font: 'fraunces-latin-var.woff2' | 'inter-latin-var.woff2'): string {
  return `${emailAssetBaseUrl()}/fonts/${font}`;
}
