/**
 * UUID generation helper for request tracing.
 *
 * The primary X-Request-ID is generated by middleware.ts on every request.
 * This utility is useful for non-middleware contexts where a request ID
 * is needed (e.g., background jobs, test utilities).
 *
 * AGENTS #45: Generate a UUID per request for tracing.
 */
import { randomUUID } from 'crypto';

export function generateRequestId(): string {
  return randomUUID();
}
