// Tailwind config for the design-sync export.
// Spreads apps/web's config verbatim so the full semantic colour system,
// elevation ladder and font-size scale are preserved. Only `content` and
// `safelist` differ.
import base from '../apps/web/tailwind.config';

export default {
  ...base,
  // `relative: true` is REQUIRED: v3 content globs resolve against the CWD,
  // not the config file. Without it a run from the repo root silently
  // produces a near-empty stylesheet.
  content: {
    relative: true,
    files: [
      '../apps/web/src/components/**/*.{ts,tsx}',
      '../apps/web/src/app/**/*.{ts,tsx}',
      '../packages/ui/src/**/*.{ts,tsx}',
      // Full semantic vocabulary (generated by .ds-sync/gen-vocabulary.mjs).
      // Without this the sheet is JIT-scoped to classes EXISTING components
      // use, so a NEW design written by the design agent using any unused
      // semantic class would emit zero CSS and render silently unstyled.
      './vocabulary.txt',
    ],
  },
  // Literal strings ONLY - never patterns (they explode against variants and
  // under-cover silently). This is preview-harness vocabulary the app itself
  // doesn't happen to use; component classes come from the content scan above.
  safelist: [
    'p-6', 'p-8', 'gap-6', 'gap-8', 'space-y-6', 'space-y-8',
    'grid', 'grid-cols-5', 'grid-cols-6',
    'sm:grid-cols-2', 'sm:grid-cols-3', 'md:grid-cols-3', 'md:grid-cols-4',
    'lg:grid-cols-4', 'lg:grid-cols-6',
    'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'w-64', 'w-80', 'w-96', 'h-64', 'h-80',
    'text-content-tertiary', 'uppercase', 'tracking-wide',
    'flex-wrap', 'items-start', 'items-end', 'justify-center', 'justify-start',
    'shrink-0', 'grow',
  ],
};
