import { useMemo } from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  FileText,
  CalendarDays,
  Megaphone,
  Wrench,
  CreditCard,
  Package,
  UserCheck,
  Settings,
  ShieldCheck,
  AlertTriangle,
  Inbox,
  PenTool,
  FileSignature,
  ClipboardList,
  Home,
  Truck,
  ScrollText,
  BarChart3,
  DollarSign,
  Upload,
  Bell,
  CalendarPlus,
  FilePlus,
  Send,
  Siren,
  Download,
  CircleGauge,
  HelpCircle,
  Building2,
  Vote,
  MessageSquare,
  Columns3,
  BookOpen,
  Landmark,
  ClipboardCheck,
} from 'lucide-react';
import type { CommunityRole, AnyCommunityRole, CommunityFeatures } from '@propertypro/shared';
import { ADMIN_ROLES } from '@propertypro/shared';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type RegistryCategory = 'page' | 'action' | 'setting';
export type RegistryAudience = 'resident' | 'admin' | 'all';

export interface FeatureRegistryItem {
  id: string;
  label: string;
  keywords: string[];
  description: string;
  icon: LucideIcon;
  href: string | ((communityId: number) => string);
  roles: 'all' | readonly CommunityRole[];
  audience: RegistryAudience;
  category: RegistryCategory;
  group: string;
  featureFlag?: keyof CommunityFeatures;
}

export interface ResolvedRegistryItem extends Omit<FeatureRegistryItem, 'href'> {
  href: string;
  resolvedHref: string;
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const FEATURE_REGISTRY: FeatureRegistryItem[] = [
  // ========================================================================
  // PAGES — audience: 'all'
  // ========================================================================
  {
    id: 'page-dashboard',
    label: 'Dashboard',
    keywords: ['home', 'overview', 'summary', 'hub', 'main', 'start', 'landing'],
    description: 'Your community overview and quick actions',
    icon: LayoutDashboard,
    href: '/dashboard',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
  },
  {
    id: 'page-documents',
    label: 'Documents',
    keywords: ['documents', 'files', 'records', 'library', 'pdf', 'upload', 'download', 'bylaws', 'rules', 'minutes', 'budget'],
    description: 'Community documents and records library',
    icon: FileText,
    href: (cid: number) => `/communities/${cid}/documents`,
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
  },
  {
    id: 'page-meetings',
    label: 'Meetings',
    keywords: ['meeting', 'calendar', 'schedule', 'agenda', 'board meeting', 'annual', 'notice', 'minutes', 'quorum'],
    description: 'Meeting calendar, agendas, and notices',
    icon: CalendarDays,
    href: (cid: number) => `/communities/${cid}/meetings`,
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
    featureFlag: 'hasMeetings',
  },
  {
    id: 'page-announcements',
    label: 'Announcements',
    keywords: ['announcement', 'news', 'bulletin', 'notify', 'updates', 'broadcast', 'message', 'alert', 'communication'],
    description: 'Community announcements and bulletins',
    icon: Megaphone,
    href: '/announcements',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
  },
  {
    id: 'page-maintenance',
    label: 'Maintenance',
    keywords: ['maintenance', 'repair', 'fix', 'broken', 'work order', 'help', 'issue', 'problem', 'leak', 'damage', 'plumbing', 'electrical', 'hvac', 'pool', 'elevator'],
    description: 'Submit and track maintenance requests',
    icon: Wrench,
    href: '/maintenance/submit',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
    featureFlag: 'hasMaintenanceRequests',
  },
  {
    id: 'page-payments',
    label: 'Payments',
    keywords: ['payment', 'pay', 'dues', 'assessment', 'balance', 'bill', 'fee', 'invoice', 'amount owed', 'charges'],
    description: 'View balances and make payments',
    icon: CreditCard,
    href: (cid: number) => `/communities/${cid}/payments`,
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Finance',
    featureFlag: 'hasFinance',
  },
  {
    id: 'page-packages',
    label: 'Packages',
    keywords: ['package', 'delivery', 'mail', 'amazon', 'ups', 'fedex', 'parcel', 'pickup', 'mailroom'],
    description: 'Track incoming packages and deliveries',
    icon: Package,
    href: '/dashboard/packages',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Services',
    featureFlag: 'hasPackageLogging',
  },
  {
    id: 'page-visitors',
    label: 'Visitors',
    keywords: ['visitor', 'guest', 'access', 'entry', 'gate', 'front desk', 'pass', 'check in', 'check out'],
    description: 'Manage visitor passes and guest access',
    icon: UserCheck,
    href: '/dashboard/visitors',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Services',
    featureFlag: 'hasVisitorLogging',
  },
  {
    id: 'page-settings',
    label: 'Settings',
    keywords: ['settings', 'preferences', 'account', 'profile', 'configuration', 'my account', 'personal'],
    description: 'Account settings and preferences',
    icon: Settings,
    href: '/settings',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Account',
  },
  {
    id: 'page-help',
    label: 'Help Center',
    keywords: ['help', 'support', 'faq', 'how to', 'guide', 'learn', 'tutorial', 'documentation', 'question', 'stuck', 'confused'],
    description: 'FAQs, guides, and support resources',
    icon: HelpCircle,
    href: '/help',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Support',
  },

  // ========================================================================
  // PAGES — audience: 'admin'
  // ========================================================================
  {
    id: 'page-compliance',
    label: 'Compliance Dashboard',
    keywords: ['compliance', 'score', 'status', 'health', 'audit', '718', 'statute', 'regulation', 'statutory', 'requirements'],
    description: 'Community compliance status and scoring',
    icon: ShieldCheck,
    href: (cid: number) => `/communities/${cid}/compliance`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Compliance',
    featureFlag: 'hasCompliance',
  },
  {
    id: 'page-violations-inbox',
    label: 'Violations Inbox',
    keywords: ['violation', 'complaint', 'rule', 'infraction', 'notice', 'hearing', 'fine', 'penalty', 'enforcement'],
    description: 'Review and manage violation cases',
    icon: AlertTriangle,
    href: '/violations/inbox',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Compliance',
    featureFlag: 'hasViolations',
  },
  {
    id: 'page-maintenance-inbox',
    label: 'Maintenance Inbox',
    keywords: ['maintenance inbox', 'work orders', 'service requests', 'repair queue', 'assigned', 'pending repairs', 'open tickets'],
    description: 'Manage and assign maintenance work orders',
    icon: Inbox,
    href: '/maintenance/inbox',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
    featureFlag: 'hasMaintenanceRequests',
  },
  {
    id: 'page-esign',
    label: 'E-Sign',
    keywords: ['esign', 'signature', 'sign', 'document signing', 'template', 'contract', 'agreement', 'docusign', 'electronic signature'],
    description: 'E-signature templates and submissions',
    icon: PenTool,
    href: '/esign',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Documents',
    featureFlag: 'hasEsign',
  },
  {
    id: 'page-contracts',
    label: 'Contracts',
    keywords: ['contract', 'vendor', 'agreement', 'bid', 'service provider', 'contractor', 'proposal', 'scope of work'],
    description: 'Vendor contracts and service agreements',
    icon: FileSignature,
    href: '/contracts',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
  },
  {
    id: 'page-leases',
    label: 'Leases',
    keywords: ['lease', 'tenant', 'renter', 'unit', 'occupancy', 'renewal', 'expiration', 'rental', 'apartment'],
    description: 'Lease tracking and renewal management',
    icon: Home,
    href: '/dashboard/leases',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
    featureFlag: 'hasLeaseTracking',
  },
  {
    id: 'page-move-in-out',
    label: 'Move In/Out',
    keywords: ['move', 'checklist', 'turnover', 'unit prep', 'move-in', 'move-out', 'vacate', 'inspection', 'walkthrough'],
    description: 'Move-in/out checklists and unit turnover',
    icon: Truck,
    href: '/dashboard/move-in-out',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
    featureFlag: 'hasLeaseTracking',
  },
  {
    id: 'page-audit-trail',
    label: 'Audit Trail',
    keywords: ['audit', 'log', 'activity', 'history', 'changes', 'trail', 'compliance log', 'who changed', 'record'],
    description: 'Activity log and compliance audit trail',
    icon: ScrollText,
    href: '/audit-trail',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Compliance',
  },
  {
    id: 'page-finance',
    label: 'Finance Dashboard',
    keywords: ['finance', 'revenue', 'income', 'report', 'analytics', 'financial', 'accounting', 'money', 'budget', 'expense'],
    description: 'Financial overview, reports, and analytics',
    icon: BarChart3,
    href: (cid: number) => `/communities/${cid}/finance`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Finance',
    featureFlag: 'hasFinance',
  },
  {
    id: 'page-assessments',
    label: 'Assessments',
    keywords: ['assessment', 'dues', 'fee schedule', 'billing', 'charge', 'special assessment', 'quarterly', 'monthly', 'delinquent'],
    description: 'Assessment billing and fee schedules',
    icon: DollarSign,
    href: (cid: number) => `/communities/${cid}/assessments`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Finance',
    featureFlag: 'hasFinance',
  },
  {
    id: 'page-residents',
    label: 'Residents',
    keywords: ['resident', 'owner', 'tenant', 'member', 'directory', 'contact', 'unit', 'who lives'],
    description: 'Resident directory and unit assignments',
    icon: Building2,
    href: '/dashboard/residents',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
  },
  {
    id: 'page-voting',
    label: 'Voting',
    keywords: ['vote', 'election', 'ballot', 'proxy', 'quorum', 'board election', 'poll', 'referendum'],
    description: 'Elections, ballots, and voting management',
    icon: Vote,
    href: (cid: number) => `/communities/${cid}/voting`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Governance',
    featureFlag: 'hasVoting',
  },
  {
    id: 'page-community-board',
    label: 'Community Board',
    keywords: ['forum', 'board', 'discussion', 'community', 'post', 'conversation', 'social'],
    description: 'Community discussion board',
    icon: MessageSquare,
    href: '/community-board',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Community',
    featureFlag: 'hasCommunityBoard',
  },
  {
    id: 'page-amenities',
    label: 'Amenities',
    keywords: ['amenity', 'reserve', 'book', 'pool', 'gym', 'clubhouse', 'tennis', 'room', 'reservation'],
    description: 'Reserve amenities and common areas',
    icon: Landmark,
    href: '/amenities',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Services',
    featureFlag: 'hasAmenities',
  },
  {
    id: 'page-arc',
    label: 'ARC Applications',
    keywords: ['arc', 'architectural', 'review', 'modification', 'renovation', 'improvement', 'application', 'approval', 'exterior'],
    description: 'Architectural review applications',
    icon: ClipboardCheck,
    href: '/arc',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Governance',
    featureFlag: 'hasARC',
  },
  {
    id: 'page-calendar',
    label: 'Calendar',
    keywords: ['calendar', 'events', 'upcoming', 'date', 'schedule', 'ical', 'sync', 'google calendar'],
    description: 'Community event calendar and sync',
    icon: CalendarDays,
    href: '/calendar',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'General',
    featureFlag: 'hasCalendarSync',
  },
  {
    id: 'page-polls',
    label: 'Polls',
    keywords: ['poll', 'survey', 'question', 'feedback', 'opinion', 'community input', 'vote'],
    description: 'View and respond to community polls',
    icon: Columns3,
    href: '/polls',
    roles: 'all',
    audience: 'all',
    category: 'page',
    group: 'Community',
    featureFlag: 'hasPolls',
  },
  {
    id: 'page-work-orders',
    label: 'Work Orders',
    keywords: ['work order', 'vendor', 'dispatch', 'assign', 'technician', 'contractor', 'service call'],
    description: 'Vendor work order dispatch and tracking',
    icon: ClipboardList,
    href: '/work-orders',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Operations',
    featureFlag: 'hasWorkOrders',
  },
  {
    id: 'page-public-notices',
    label: 'Public Notices',
    keywords: ['public', 'notice', 'statutory', 'posting', 'required', 'public record', 'transparency'],
    description: 'Statutorily required public notice postings',
    icon: BookOpen,
    href: (cid: number) => `/communities/${cid}/public-notices`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'page',
    group: 'Compliance',
    featureFlag: 'hasPublicNoticesPage',
  },

  // ========================================================================
  // ACTIONS — audience: 'all'
  // ========================================================================
  {
    id: 'action-submit-maintenance',
    label: 'Submit Maintenance Request',
    keywords: ['submit', 'maintenance', 'repair', 'fix', 'broken', 'work order', 'help', 'issue', 'problem', 'leak', 'damage', 'plumbing', 'electrical', 'hvac', 'toilet', 'ac', 'water', 'flood', 'mold', 'pest'],
    description: 'Report something that needs repair',
    icon: Wrench,
    href: '/maintenance/submit',
    roles: 'all',
    audience: 'all',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasMaintenanceRequests',
  },
  {
    id: 'action-report-violation',
    label: 'Report a Violation',
    keywords: ['violation', 'report', 'complaint', 'rule', 'noise', 'parking', 'pet', 'trash', 'debris', 'neighbor', 'loud', 'nuisance'],
    description: 'Report a rule or covenant violation',
    icon: AlertTriangle,
    href: '/violations/report',
    roles: 'all',
    audience: 'all',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasViolations',
  },
  {
    id: 'action-submit-arc',
    label: 'Submit ARC Application',
    keywords: ['arc', 'architectural', 'submit', 'modification', 'renovation', 'improvement', 'exterior', 'paint', 'fence', 'window'],
    description: 'Submit an architectural review application',
    icon: ClipboardCheck,
    href: '/arc',
    roles: 'all',
    audience: 'all',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasARC',
  },
  {
    id: 'action-reserve-amenity',
    label: 'Reserve Amenity',
    keywords: ['reserve', 'book', 'amenity', 'pool', 'gym', 'clubhouse', 'room', 'court', 'reservation'],
    description: 'Book a community amenity or common area',
    icon: Landmark,
    href: '/amenities',
    roles: 'all',
    audience: 'all',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasAmenities',
  },

  // ========================================================================
  // ACTIONS — audience: 'admin'
  // ========================================================================
  {
    id: 'action-upload-document',
    label: 'Upload Document',
    keywords: ['upload', 'file', 'pdf', 'add', 'attach', 'post', 'new document', 'scan', 'import'],
    description: 'Upload a new document to the library',
    icon: Upload,
    href: (cid: number) => `/communities/${cid}/documents`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
  },
  {
    id: 'action-post-announcement',
    label: 'Post Announcement',
    keywords: ['announce', 'post', 'broadcast', 'notify', 'send', 'communicate', 'bulletin', 'news', 'message', 'alert', 'blast'],
    description: 'Send a new announcement to residents',
    icon: Megaphone,
    href: '/announcements',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
  },
  {
    id: 'action-schedule-meeting',
    label: 'Schedule Meeting',
    keywords: ['schedule', 'meeting', 'create', 'new meeting', 'board meeting', 'annual', 'notice', 'agenda', 'plan', 'organize'],
    description: 'Create a new meeting with notice',
    icon: CalendarPlus,
    href: (cid: number) => `/communities/${cid}/meetings`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasMeetings',
  },
  {
    id: 'action-create-esign-template',
    label: 'Create E-Sign Template',
    keywords: ['esign', 'template', 'create', 'new', 'sign', 'signature', 'form', 'contract', 'build'],
    description: 'Design a new e-signature template',
    icon: FilePlus,
    href: '/esign/templates/new',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasEsign',
  },
  {
    id: 'action-send-esign',
    label: 'Send E-Sign Document',
    keywords: ['send', 'esign', 'document', 'sign', 'collect signatures', 'submit for signing', 'request signature'],
    description: 'Send a document for electronic signature',
    icon: Send,
    href: '/esign/submissions/new',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasEsign',
  },
  {
    id: 'action-emergency-broadcast',
    label: 'Send Emergency Broadcast',
    keywords: ['emergency', 'urgent', 'broadcast', 'alert', 'critical', 'notification', 'push', 'sms', 'evacuation', 'storm', 'hurricane'],
    description: 'Send an urgent notification to all residents',
    icon: Siren,
    href: '/emergency/new',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasEmergencyNotifications',
  },
  {
    id: 'action-record-violation',
    label: 'Record Violation',
    keywords: ['create violation', 'new violation', 'issue notice', 'fine', 'penalty', 'infraction', 'enforce'],
    description: 'Create a new violation case against a unit',
    icon: ClipboardList,
    href: '/violations/inbox',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasViolations',
  },
  {
    id: 'action-add-resident',
    label: 'Add Resident',
    keywords: ['add resident', 'new owner', 'new tenant', 'invite', 'onboard', 'register', 'new member', 'move in'],
    description: 'Add a new resident to the community',
    icon: UserCheck,
    href: '/dashboard/residents',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
  },
  {
    id: 'action-create-poll',
    label: 'Create Poll',
    keywords: ['poll', 'survey', 'question', 'ask', 'feedback', 'opinion', 'vote', 'informal'],
    description: 'Create an informal community poll',
    icon: Columns3,
    href: '/polls/new',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasPolls',
  },
  {
    id: 'action-dispatch-work-order',
    label: 'Dispatch Work Order',
    keywords: ['dispatch', 'work order', 'vendor', 'assign', 'send', 'contractor', 'technician', 'schedule repair'],
    description: 'Dispatch a work order to a vendor',
    icon: ClipboardList,
    href: '/work-orders',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasWorkOrders',
  },
  {
    id: 'action-generate-report',
    label: 'Generate Report',
    keywords: ['report', 'generate', 'export', 'analytics', 'summary', 'monthly', 'quarterly', 'annual', 'financial report'],
    description: 'Generate a community or financial report',
    icon: BarChart3,
    href: (cid: number) => `/communities/${cid}/finance`,
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'action',
    group: 'Quick Actions',
    featureFlag: 'hasFinance',
  },

  // ========================================================================
  // SETTINGS — audience: 'all'
  // ========================================================================
  {
    id: 'setting-notifications',
    label: 'Notification Preferences',
    keywords: ['notifications', 'email', 'alerts', 'preferences', 'unsubscribe', 'frequency', 'digest', 'mute', 'opt out'],
    description: 'Control how and when you receive notifications',
    icon: Bell,
    href: '/settings',
    roles: 'all',
    audience: 'all',
    category: 'setting',
    group: 'Account',
  },
  {
    id: 'setting-data-export',
    label: 'Data Export',
    keywords: ['export', 'download', 'csv', 'data', 'backup', 'records', 'my data', 'personal data'],
    description: 'Export your data and records',
    icon: Download,
    href: '/settings/export',
    roles: 'all',
    audience: 'all',
    category: 'setting',
    group: 'Account',
  },

  // ========================================================================
  // SETTINGS — audience: 'admin'
  // ========================================================================
  {
    id: 'setting-payments',
    label: 'Payment Settings',
    keywords: ['stripe', 'payment settings', 'billing configuration', 'connect', 'payment processor', 'bank account', 'payout'],
    description: 'Configure payment processing and Stripe',
    icon: CreditCard,
    href: '/settings/payments',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'setting',
    group: 'Administration',
    featureFlag: 'hasFinance',
  },
  {
    id: 'setting-transparency',
    label: 'Transparency Settings',
    keywords: ['transparency', 'sirs', 'public page', 'inspection', 'building', 'milestone', 'structural'],
    description: 'Configure public transparency and SIRS pages',
    icon: CircleGauge,
    href: '/settings/transparency',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'setting',
    group: 'Administration',
    featureFlag: 'hasTransparencyPage',
  },
  {
    id: 'setting-community',
    label: 'Community Settings',
    keywords: ['community settings', 'association', 'name', 'address', 'logo', 'branding', 'customize'],
    description: 'Edit community details and branding',
    icon: Building2,
    href: '/settings/community',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'setting',
    group: 'Administration',
  },
  {
    id: 'setting-roles',
    label: 'Roles & Permissions',
    keywords: ['roles', 'permissions', 'access', 'who can', 'admin', 'board', 'manager', 'staff', 'user management'],
    description: 'Manage user roles and access permissions',
    icon: BookOpen,
    href: '/settings/roles',
    roles: ADMIN_ROLES,
    audience: 'admin',
    category: 'setting',
    group: 'Administration',
  },
] satisfies FeatureRegistryItem[];

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

/**
 * Returns the feature registry filtered by role and enabled feature flags,
 * with all `href` functions resolved to concrete strings.
 */
export function useFilteredRegistry(
  role: AnyCommunityRole | null,
  features: CommunityFeatures | null,
  communityId: number | null,
): ResolvedRegistryItem[] {
  return useMemo(() => {
    return (FEATURE_REGISTRY as readonly FeatureRegistryItem[])
      .filter((item) => {
        // Role check
        if (item.roles !== 'all') {
          if (!role) return false;
          if (!(item.roles as readonly string[]).includes(role)) return false;
        }
        // Feature flag check
        if (item.featureFlag && features) {
          if (!features[item.featureFlag]) return false;
        }
        return true;
      })
      .map((item) => {
        const resolvedHref =
          typeof item.href === 'function' && communityId
            ? item.href(communityId)
            : typeof item.href === 'string'
              ? item.href
              : '#';

        return {
          ...item,
          href: resolvedHref,
          resolvedHref,
        };
      });
  }, [role, features, communityId]);
}
