/**
 * RBAC Parity Tests
 *
 * These tests verify that the new 4-role system produces identical permission
 * results as the old 7-role system. They compare the output of the new
 * checkPermission(RoleContext, ...) and canAccessCategory(RoleContext, ...)
 * against the frozen JSON snapshots generated before the migration.
 *
 * The snapshots were generated by generate-rbac-snapshots.ts using the
 * original 7-role checkPermission() and canAccessCategory() functions.
 *
 * Run: npx vitest run packages/shared/src/__tests__/rbac-parity.test.ts
 */

import { describe, it, expect } from 'vitest';

import { COMMUNITY_ROLES, COMMUNITY_TYPES } from '../index';
import type { CommunityRole, CommunityType } from '../index';
import { RBAC_RESOURCES, RBAC_ACTIONS, checkPermission } from '../rbac-matrix';
import type { RbacResource, RbacAction } from '../rbac-matrix';
import {
  DOCUMENT_CATEGORY_KEYS,
  canAccessCategory,
} from '../access-policies';
import type { DocumentCategoryKey } from '../access-policies';

import rbacSnapshot from './fixtures/rbac-snapshot.json' with { type: 'json' };
import docAccessSnapshot from './fixtures/document-access-snapshot.json' with { type: 'json' };

// Type-safe snapshot accessors
type SnapshotRbac = Record<string, Record<string, Record<string, Record<string, boolean>>>>;
type SnapshotDoc = Record<string, Record<string, Record<string, boolean>>>;
const rbac = rbacSnapshot as SnapshotRbac;
const docAccess = docAccessSnapshot as SnapshotDoc;

// ---------------------------------------------------------------------------
// Role mapping: old 7-role → new RoleContext
// ---------------------------------------------------------------------------

// TODO: Import these from the new system once Phase 3a is implemented
// import type { RoleContext } from '../index';
// import type { ManagerPermissions } from '../manager-permissions';
// import { MANAGER_PRESETS } from '../manager-presets';

interface RoleContext {
  role: 'resident' | 'manager' | 'pm_admin';
  isUnitOwner?: boolean;
  permissions?: {
    resources: Record<string, { read: boolean; write: boolean }>;
    document_categories: 'all' | string[];
    can_manage_roles: boolean;
    can_manage_settings: boolean;
    is_board_member: boolean;
  };
}

/**
 * Maps each old 7-role to the equivalent RoleContext in the new system.
 * The permissions for managers are derived from the snapshot itself (since
 * the preset JSONB will be backfilled from the same RBAC matrix data).
 *
 * This function builds the RoleContext dynamically from the snapshot so the
 * test is self-contained and doesn't depend on preset definitions.
 */
function oldRoleToRoleContext(
  role: CommunityRole,
  communityType: CommunityType,
): RoleContext {
  switch (role) {
    case 'owner':
      return { role: 'resident', isUnitOwner: true };
    case 'tenant':
      return { role: 'resident', isUnitOwner: false };
    case 'property_manager_admin':
      return { role: 'pm_admin' };
    case 'board_member':
    case 'board_president':
    case 'cam':
    case 'site_manager': {
      // Build manager permissions from the snapshot (same data that will be backfilled)
      const roleSnapshot = rbac[communityType]![role]!;
      const resources: Record<string, { read: boolean; write: boolean }> = {};
      for (const resource of RBAC_RESOURCES) {
        resources[resource] = {
          read: roleSnapshot[resource]?.read ?? false,
          write: roleSnapshot[resource]?.write ?? false,
        };
      }

      const docSnapshot = docAccess[communityType]![role]!;
      // Determine document_categories from snapshot
      const allCategoriesAccessible = Object.entries(docSnapshot)
        .filter(([key]) => key !== 'unknown')
        .every(([, val]) => val === true);
      const document_categories: 'all' | string[] = allCategoriesAccessible
        ? 'all'
        : Object.entries(docSnapshot)
            .filter(([key, val]) => key !== 'unknown' && val === true)
            .map(([key]) => key);

      return {
        role: 'manager',
        permissions: {
          resources,
          document_categories,
          can_manage_roles: role === 'board_president' || role === 'cam' || role === 'site_manager',
          can_manage_settings: role === 'board_president',
          is_board_member: role === 'board_member' || role === 'board_president',
        },
      };
    }
    default:
      throw new Error(`Unknown role: ${role}`);
  }
}

// ---------------------------------------------------------------------------
// RBAC Parity Tests
// ---------------------------------------------------------------------------

describe('RBAC parity: new 4-role system matches old 7-role system', () => {
  // Test each old role individually for clear failure messages
  for (const communityType of COMMUNITY_TYPES) {
    for (const role of COMMUNITY_ROLES) {
      describe(`${communityType} / ${role}`, () => {
        const ctx = oldRoleToRoleContext(role, communityType);

        for (const resource of RBAC_RESOURCES) {
          for (const action of RBAC_ACTIONS) {
            const expected = rbac[communityType]![role]![resource]![action]!;

            it(`${resource}.${action} should be ${expected}`, () => {
              // TODO: Replace with new checkPermission(ctx, communityType, resource, action)
              // once Phase 3a is implemented. For now, test the old system against itself.
              const actual = checkPermission(role, communityType, resource, action);
              expect(actual).toBe(expected);
            });
          }
        }
      });
    }
  }
});

// ---------------------------------------------------------------------------
// Document Access Parity Tests
// ---------------------------------------------------------------------------

describe('Document access parity: new 4-role system matches old 7-role system', () => {
  for (const communityType of COMMUNITY_TYPES) {
    for (const role of COMMUNITY_ROLES) {
      describe(`${communityType} / ${role}`, () => {
        for (const categoryKey of DOCUMENT_CATEGORY_KEYS) {
          const expected = docAccess[communityType]![role]![categoryKey]!;

          it(`canAccessCategory('${categoryKey}') should be ${expected}`, () => {
            // TODO: Replace with new canAccessCategory(ctx, communityType, categoryKey)
            // once Phase 3a is implemented. For now, test the old system against itself.
            const actual = canAccessCategory(role, communityType, categoryKey);
            expect(actual).toBe(expected);
          });
        }
      });
    }
  }
});
