// GENERATED by .ds-sync/gen-barrel.mjs — do not hand-edit.
// Code-truth design-system barrel: packages/ui + apps/web shadcn + shared.
// Relative imports only: root node_modules/@propertypro holds just `db`,
// so bare specifiers do NOT resolve from .design-sync/.

// MUST be first — installs the `process` shim before any next/* module evaluates.
export { PROCESS_SHIM } from './process-shim';

// --- @propertypro/ui (18) ---
export { Badge, PriorityBadge, StatusBadge as UiStatusBadge } from '../../packages/ui/src/components/Badge';
export { PlanBadge } from '../../packages/ui/src/components/PlanBadge';
export { NavRail } from '../../packages/ui/src/components/NavRail';
export { PhoneFrame } from '../../packages/ui/src/components/PhoneFrame';
export { Box } from '../../packages/ui/src/primitives/Box';
export { Stack, HStack, VStack, Center, Spacer } from '../../packages/ui/src/primitives/Stack';
export { Text, Heading, Label as UiLabel, Caption, Code, Paragraph } from '../../packages/ui/src/primitives/Text';

// --- apps/web components (129) ---
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger } from '../../apps/web/src/components/ui/alert-dialog';
export { Badge as ShadcnBadge } from '../../apps/web/src/components/ui/badge';
export { Button } from '../../apps/web/src/components/ui/button';
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../../apps/web/src/components/ui/card';
export { ChartContainer, ChartLegend, ChartLegendContent, ChartStyle, ChartTooltip, ChartTooltipContent } from '../../apps/web/src/components/ui/chart';
export { Checkbox } from '../../apps/web/src/components/ui/checkbox';
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from '../../apps/web/src/components/ui/command';
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger } from '../../apps/web/src/components/ui/dialog';
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from '../../apps/web/src/components/ui/dropdown-menu';
export { HelpTooltip } from '../../apps/web/src/components/ui/help-tooltip';
export { Input } from '../../apps/web/src/components/ui/input';
export { Label } from '../../apps/web/src/components/ui/label';
export { Popover, PopoverAnchor, PopoverContent, PopoverTrigger } from '../../apps/web/src/components/ui/popover';
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue } from '../../apps/web/src/components/ui/select';
export { Separator } from '../../apps/web/src/components/ui/separator';
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetOverlay, SheetPortal, SheetTitle, SheetTrigger } from '../../apps/web/src/components/ui/sheet';
export { Skeleton } from '../../apps/web/src/components/ui/skeleton';
export { Switch } from '../../apps/web/src/components/ui/switch';
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from '../../apps/web/src/components/ui/table';
export { Tabs, TabsContent, TabsList, TabsTrigger } from '../../apps/web/src/components/ui/tabs';
export { Textarea } from '../../apps/web/src/components/ui/textarea';
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '../../apps/web/src/components/ui/tooltip';
export { ResidentSearchCombobox } from '../../apps/web/src/components/shared/ResidentSearchCombobox';
export { UnitSearchCombobox } from '../../apps/web/src/components/shared/UnitSearchCombobox';
export { UserSearchCombobox } from '../../apps/web/src/components/shared/UserSearchCombobox';
export { AlertBanner } from '../../apps/web/src/components/shared/alert-banner';
export { BulkActionBar } from '../../apps/web/src/components/shared/bulk-action-bar';
export { ChartEmptyState } from '../../apps/web/src/components/shared/chart-empty-state';
export { ChartSkeleton } from '../../apps/web/src/components/shared/chart-skeleton';
export { ChecklistStepper } from '../../apps/web/src/components/shared/checklist-stepper';
export { CsvExportButton } from '../../apps/web/src/components/shared/csv-export-button';
export { DataTableColumnHeader } from '../../apps/web/src/components/shared/data-table-column-header';
export { DataTablePagination } from '../../apps/web/src/components/shared/data-table-pagination';
export { DataTable } from '../../apps/web/src/components/shared/data-table';
export { EmptyState } from '../../apps/web/src/components/shared/empty-state';
export { KpiCard } from '../../apps/web/src/components/shared/kpi-card';
export { PageBody } from '../../apps/web/src/components/shared/page-body';
export { PageHeaderHelpButton } from '../../apps/web/src/components/shared/page-header-help-button';
export { PageHeader } from '../../apps/web/src/components/shared/page-header';
export { QuickFilterTabs } from '../../apps/web/src/components/shared/quick-filter-tabs';
export { SlideOverPanel } from '../../apps/web/src/components/shared/slide-over-panel';
export { StatusBadge, StatusDot } from '../../apps/web/src/components/shared/status-badge';
export { PageContainer } from '../../apps/web/src/components/layout/page-container';
