#!/usr/bin/env bash
set -euo pipefail

# Standardized wrapper for local verification commands that require .env.local.
#
# ## This wrapper targets PRODUCTION
#
# `.env.local`'s DATABASE_URL, Supabase and Upstash all point at production. That
# is the whole reason this wrapper exists — and it is why NEXT_PUBLIC_APP_URL has
# to be corrected on the way through.
#
# `.env.local` sets NEXT_PUBLIC_APP_URL=http://localhost:3000, which is right for
# `next dev` and wrong for anything this wrapper runs. `getBaseUrl()`
# (apps/web/src/lib/utils/url.ts) has 26 callers and essentially all of them build
# a link inside an OUTBOUND EMAIL: invitations, password reset, signup
# verification, announcement digests, emergency broadcasts, payment alerts,
# access requests. Run an ops script through this wrapper without the override
# below and every one of those emails reaches a real recipient carrying a
# `http://localhost:3000/...` link that can only work on the sender's laptop.
#
# The invariant is the mirror of the one in with-env-local-demo-db.sh: there, a
# local database implies local Supabase; here, a PRODUCTION database implies
# PRODUCTION URLs. A half-redirected env is the dangerous state in both
# directions, because it looks local and acts remote.
#
# The default matches the value actually configured on Vercel production, so a
# link generated here is byte-identical to one generated by the deployed app.
# Override with PROPERTYPRO_APP_URL when targeting somewhere else (a preview
# deployment, say).

usage() {
  cat <<'EOF'
Usage:
  scripts/with-env-local.sh <command> [args...]

Examples:
  scripts/with-env-local.sh pnpm --filter @propertypro/db test:integration
  scripts/with-env-local.sh pnpm test:integration:preflight

Note: this wrapper targets PRODUCTION (that is what .env.local points at), so it
forces NEXT_PUBLIC_APP_URL to the production app URL rather than the localhost
value in the env file. Otherwise any email an ops script sends carries a
localhost link. Override with PROPERTYPRO_APP_URL.
EOF
}

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 64
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
env_file="$repo_root/.env.local"

if [[ ! -f "$env_file" ]]; then
  echo "Missing required env file: $env_file" >&2
  exit 66
fi

# Capture a caller-provided NODE_ENV (e.g. `NODE_ENV=staging scripts/…`) so
# we can preserve it across sourcing. `${VAR+x}` is the nounset-safe way to
# test whether a variable was set at all.
_caller_node_env_set="${NODE_ENV+x}"
_caller_node_env="${NODE_ENV-}"

set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

# Drop any NODE_ENV contributed by .env.local, but restore a caller-provided
# override if there was one. Why: older .env.local files (see .env.example
# history) set `NODE_ENV=development`, which breaks `next build` — Next's
# `module.compiled.js` picks `pages.runtime.dev.js` when NODE_ENV=development
# while the build pipeline is compiled for production. The two runtimes ship
# different `HtmlContext` instances, so the Pages-Router `<Html>` consumer
# reads a different context than the render-pipeline Provider, and prerender
# of `/_error: /404` throws "<Html> should not be imported outside of
# pages/_document". Absent an explicit caller value, let downstream commands
# (next build/dev, vitest, etc.) set NODE_ENV themselves.
if [[ -n "$_caller_node_env_set" ]]; then
  export NODE_ENV="$_caller_node_env"
else
  unset NODE_ENV
fi
unset _caller_node_env_set _caller_node_env

# --- Base URL follows the database to production -----------------------------
#
# See the header. `source` above ran under `set -a`, so it has already clobbered
# anything the caller exported on the command line — which is why this override
# has to happen here, after the source, rather than being left to the caller.
export NEXT_PUBLIC_APP_URL="${PROPERTYPRO_APP_URL:-https://getpropertypro.com}"

# Fail loudly rather than quietly emailing a localhost link to a real person.
#
# Host extraction, then an exact host match — deliberately the same shape as
# `host_of` + `assert_loopback` in with-env-local-demo-db.sh, just inverted
# (that script demands loopback; this one refuses it). A naive `*localhost*`
# substring test both over- and under-matches: it rejects a legitimate
# `notlocalhost.example.com`, and it lets `127.1`, `0.0.0.0`, `2130706433` and a
# trailing-dot `localhost.` through — all of which resolve to loopback.
host_of() {
  # strip scheme, then credentials, then path/query, then :port, then trailing dot
  printf '%s' "$1" \
    | sed -E 's#^[a-zA-Z][a-zA-Z0-9+.-]*://##; s#^[^@/]*@##; s#[/?].*$##; s#:[0-9]+$##; s#\.$##'
}

case "$(host_of "$NEXT_PUBLIC_APP_URL")" in
  localhost | *.localhost \
  | 127.* | '[::1]' | ::1 | 0.0.0.0 | '[::]' | 2130706433 \
  | host.docker.internal | *.localtest.me | localtest.me)
    cat >&2 <<EOF
REFUSING TO RUN — NEXT_PUBLIC_APP_URL is local while the database is production.

  NEXT_PUBLIC_APP_URL: $NEXT_PUBLIC_APP_URL

Every link this command puts in an outbound email would point at your laptop.
If you are targeting a local stack, use scripts/with-env-local-demo-db.sh
instead; that wrapper redirects the database too.
EOF
    exit 78
    ;;
esac

# --- Outbound mail is suppressed unless you ask for it -----------------------
#
# `.env.local` carries the PRODUCTION Resend key, and this wrapper points the
# database at production too — so an ops script run through it mails real
# customers with real tokens. Nothing about the command line says so.
#
# EMAIL_DRY_RUN makes `sendEmail`/`sendBulkEmail` (packages/email/src/send.ts)
# collect and LOG every message instead of transmitting it, so you can see who a
# job would have mailed before it does. Default ON here: the documented uses of
# this wrapper (db:migrate, seed:verify, integration suites) send no mail at all,
# so the safe default costs nothing, and the one case that does want delivery is
# rare enough to be explicit.
if [[ "${PROPERTYPRO_ALLOW_OUTBOUND_MAIL:-}" == "1" ]]; then
  unset EMAIL_DRY_RUN || true
  if [[ -n "${RESEND_API_KEY:-}" ]]; then
    cat >&2 <<'EOF'
⚠️  OUTBOUND MAIL IS LIVE — PROPERTYPRO_ALLOW_OUTBOUND_MAIL=1

Emails from this command will be delivered to real recipients via production
Resend, carrying working links and valid tokens. Unset that variable to dry-run.
EOF
  fi
else
  export EMAIL_DRY_RUN=1
  echo "[with-env-local] outbound mail is DRY-RUN (set PROPERTYPRO_ALLOW_OUTBOUND_MAIL=1 to actually send)" >&2
fi

exec "$@"
