import { readFileSync, writeFileSync } from 'node:fs';
const ROOT = '/Users/jphilistin/Documents/Coding/PropertyPro';
const app = JSON.parse(readFileSync(ROOT + '/.design-sync/.app-exports.json', 'utf8'));
const ui  = JSON.parse(readFileSync(ROOT + '/.design-sync/.ui-exports.json', 'utf8'));

// Collision policy (see plan + docs/design-system/README.md:14-15)
const UI_EXCLUDE = new Set(['Button', 'Card']);          // @deprecated for web
const UI_RENAME  = { StatusBadge: 'UiStatusBadge', Label: 'UiLabel' };
const APP_RENAME = { 'apps/web/src/components/ui/badge.tsx': { Badge: 'ShadcnBadge' } };

const L = [];
L.push('// GENERATED by .ds-sync/gen-barrel.mjs — do not hand-edit.');
L.push('// Code-truth design-system barrel: packages/ui + apps/web shadcn + shared.');
L.push('// Relative imports only: root node_modules/@propertypro holds just `db`,');
L.push('// so bare specifiers do NOT resolve from .design-sync/.');
L.push('');
L.push("// MUST be first — installs the `process` shim before any next/* module evaluates.");
L.push("export { PROCESS_SHIM } from './process-shim';");
L.push('');

// Import packages/ui components from their OWN files, never its index barrel:
// going through the barrel makes tsc emit declarations for the @deprecated
// Button/Card too, which then collide by name with the shadcn ones and make
// prop extraction pick the wrong layer.
const UI_FILES = {
  'components/Badge':      ['Badge', 'PriorityBadge', 'StatusBadge'],
  'components/PlanBadge':  ['PlanBadge'],
  'components/NavRail':    ['NavRail'],
  'components/PhoneFrame': ['PhoneFrame'],
  'primitives/Box':        ['Box'],
  'primitives/Stack':      ['Stack', 'HStack', 'VStack', 'Center', 'Spacer'],
  'primitives/Text':       ['Text', 'Heading', 'Label', 'Caption', 'Code', 'Paragraph'],
};
const uiKeep = [];
L.push('// --- @propertypro/ui (18) ---');
for (const [file, names] of Object.entries(UI_FILES)) {
  const spec = names.map((n) => { uiKeep.push(UI_RENAME[n] ?? n); return UI_RENAME[n] ? `${n} as ${UI_RENAME[n]}` : n; });
  L.push(`export { ${spec.join(', ')} } from '../../packages/ui/src/${file}';`);
}
L.push('');

let appCount = 0;
for (const [rel, names] of Object.entries(app)) {
  const ren = APP_RENAME[rel] ?? {};
  const spec = names.map((n) => (ren[n] ? `${n} as ${ren[n]}` : n));
  appCount += names.length;
  const imp = '../../' + rel.replace(/\.tsx?$/, '');
  L.push(`export { ${spec.join(', ')} } from '${imp}';`);
}
L.splice(L.length - Object.keys(app).length, 0, `// --- apps/web components (${appCount}) ---`);
L.push('');
writeFileSync(ROOT + '/.design-sync/entry/index.ts', L.join('\n'));
console.error(`packages/ui ${uiKeep.length} + app ${appCount} = ${uiKeep.length + appCount} components`);
