import type { TocItem } from '@/components/help/mdx-components';
import { slugifyHeading } from './anchors';

/**
 * Extract heading-based table-of-contents entries from raw MDX.
 *
 * Only h2 and h3 are captured — deeper levels rarely surface as top-level
 * navigation and would clutter the TOC sidebar.
 *
 * Anchor slugs are generated by the shared [slugifyHeading](./anchors.ts)
 * helper so the MDX h2/h3 renderers produce identical ids and TOC links
 * resolve correctly. Duplicate headings will share an anchor — see the
 * authoring note in `anchors.ts`.
 *
 * We parse the raw MDX (not the compiled output) so this runs on the server
 * during page render without needing a client-side mutation observer.
 */
export function extractTableOfContents(rawMdx: string): TocItem[] {
  const items: TocItem[] = [];
  const lines = rawMdx.split('\n');
  let inFence = false;

  for (const line of lines) {
    if (line.startsWith('```')) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    const match = /^(#{2,3})\s+(.+?)\s*$/.exec(line);
    if (!match) continue;
    const depth = match[1]!.length as 2 | 3;
    const rawLabel = match[2]!.trim();
    const label = rawLabel.replace(/^["']|["']$/g, '');

    items.push({ depth, label, anchor: slugifyHeading(label) });
  }

  return items;
}
